/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as AppWatchlistRouteRouteImport } from './routes/app/watchlist/route'
import { Route as AppDiscoveryRouteRouteImport } from './routes/app/discovery/route'
import { Route as AppMovieMovieIdRouteRouteImport } from './routes/app/movie/$movieId/route'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWatchlistRouteRoute = AppWatchlistRouteRouteImport.update({
  id: '/watchlist',
  path: '/watchlist',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDiscoveryRouteRoute = AppDiscoveryRouteRouteImport.update({
  id: '/discovery',
  path: '/discovery',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppMovieMovieIdRouteRoute = AppMovieMovieIdRouteRouteImport.update({
  id: '/movie/$movieId',
  path: '/movie/$movieId',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/app/discovery': typeof AppDiscoveryRouteRoute
  '/app/watchlist': typeof AppWatchlistRouteRoute
  '/login/': typeof LoginIndexRoute
  '/app/movie/$movieId': typeof AppMovieMovieIdRouteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/app/discovery': typeof AppDiscoveryRouteRoute
  '/app/watchlist': typeof AppWatchlistRouteRoute
  '/login': typeof LoginIndexRoute
  '/app/movie/$movieId': typeof AppMovieMovieIdRouteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/app/discovery': typeof AppDiscoveryRouteRoute
  '/app/watchlist': typeof AppWatchlistRouteRoute
  '/login/': typeof LoginIndexRoute
  '/app/movie/$movieId': typeof AppMovieMovieIdRouteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/discovery'
    | '/app/watchlist'
    | '/login/'
    | '/app/movie/$movieId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/app/discovery'
    | '/app/watchlist'
    | '/login'
    | '/app/movie/$movieId'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/discovery'
    | '/app/watchlist'
    | '/login/'
    | '/app/movie/$movieId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  LoginIndexRoute: typeof LoginIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/watchlist': {
      id: '/app/watchlist'
      path: '/watchlist'
      fullPath: '/app/watchlist'
      preLoaderRoute: typeof AppWatchlistRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/discovery': {
      id: '/app/discovery'
      path: '/discovery'
      fullPath: '/app/discovery'
      preLoaderRoute: typeof AppDiscoveryRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/movie/$movieId': {
      id: '/app/movie/$movieId'
      path: '/movie/$movieId'
      fullPath: '/app/movie/$movieId'
      preLoaderRoute: typeof AppMovieMovieIdRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppDiscoveryRouteRoute: typeof AppDiscoveryRouteRoute
  AppWatchlistRouteRoute: typeof AppWatchlistRouteRoute
  AppMovieMovieIdRouteRoute: typeof AppMovieMovieIdRouteRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppDiscoveryRouteRoute: AppDiscoveryRouteRoute,
  AppWatchlistRouteRoute: AppWatchlistRouteRoute,
  AppMovieMovieIdRouteRoute: AppMovieMovieIdRouteRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  LoginIndexRoute: LoginIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.ts'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
